[bootstrap.packages]
"brew-cask:alfred" = "latest"
"brew-cask:codex" = "latest"
"brew-cask:claude-code" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:linear" = "latest"
"brew-cask:notion" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:microsoft-teams" = "latest"
"brew:difftastic" = "latest"
"brew:eza" = "latest"
"brew:cliamp" = "latest"
"brew:fd" = "latest"
"brew:fzf" = "latest"
"brew:gdal" = "latest"
"brew:gh" = "latest"
"brew:git-delta" = "latest"
"brew:lazygit" = "latest"
"brew:neovim" = "latest"
"brew:ripgrep" = "latest"
"brew:starship" = "latest"
"brew:tmux" = "latest"

[settings]
dotfiles.root = "~/github.com/cloud8421/dotfiles"

[dotfiles]
"~/.config/atuin/config.toml" = {}
"~/.config/ghostty/config" = {}
"~/.config/starship.toml" = {}
"~/.config/tmux" = {}
"~/.config/nvim" = {}
"~/.gitattributes" = {}
"~/.gitconfig" = {}
"~/.gitignore_global" = {}
"~/.pi" = {}

[tools]
erlang = "29.0.5"
node = "26.7.0"
elixir = "1.20.3-otp-29"
"npm:@mariozechner/pi-coding-agent" = "latest"
